name: "Build"

on:
  push:
    branches: 
      - master
      - next
  pull_request:
    branches: 
      - master
      - next

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Build
        run: |
          npm install
          npm run build